/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

package software.amazon.smithy.java.aws.client.awsquery;

import java.math.BigInteger;
import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.Arrays;
import software.amazon.smithy.java.codecs.commons.CompactStringAccess;
import software.amazon.smithy.java.codecs.commons.NumberCodec;
import software.amazon.smithy.java.codecs.commons.TimestampCodec;

/**
 * Output buffer and parameter-name prefix stack shared by the two Query writers.
 *
 * <p>{@link QueryFormSerializer} walks a shape through {@code ShapeSerializer} and resolves each
 * name from the schema as it goes; {@link QueryFormWriter} is driven by generated bytecode that
 * already knows every static name. Both emit the same wire format, so the buffer growth policy, the
 * prefix stack, and the value encoders live here: a divergence between them is a wire-format
 * divergence, and the differential tests in {@code QueryFormSerializerTest} exist to catch one.
 *
 * <p>Methods are {@code final} so that neither subclass pays a virtual call on a hot path.
 */
abstract class QueryFormOutput {
    static final int DEFAULT_BUF_SIZE = 1024;
    static final int MAX_CACHEABLE_BUF = DEFAULT_BUF_SIZE * 4;

    /** An RFC 1123 date is at most 29 ASCII bytes, every one of which may percent-encode to three. */
    static final int MAX_HTTP_DATE_BYTES = 90;

    private static final byte[] ACTION_PREFIX = "Action=".getBytes(StandardCharsets.UTF_8);
    private static final byte[] VERSION_PREFIX = "&Version=".getBytes(StandardCharsets.UTF_8);

    byte[] buf = new byte[DEFAULT_BUF_SIZE];
    int pos;

    byte[] prefixBuf = new byte[128];
    int prefixLen;
    int[] prefixStack = new int[8];
    int prefixDepth;

    /** Scratch for the HTTP-date timestamp format, which formats before it percent-encodes. */
    private final byte[] httpDateTmp = new byte[40];

    /** Upper bound on the encoded length of {@code value}, including a sign. */
    static int maxBigIntegerBytes(BigInteger value) {
        // log10(2) is under 1/3, so one digit per three bits over-counts, and the slack covers the
        // sign and the rounding. A fixed bound cannot work: a BigInteger is arbitrarily long.
        return value.bitLength() / 3 + 4;
    }

    final void ensureCapacity(int needed) {
        int required = pos + needed;
        if (required > buf.length) {
            buf = Arrays.copyOf(buf, Math.max(required, buf.length + (buf.length >> 1)));
        }
    }

    /**
     * Returns the encoded body as a fresh array.
     *
     * <p>The copy is not incidental. Both writers are pooled, and a {@code ByteBuffer} wrapping the
     * pooled array would still alias it after the instance was handed back, so the next request on
     * the same thread would overwrite a body that had not been transmitted yet.
     */
    final ByteBuffer copyOut() {
        return ByteBuffer.wrap(Arrays.copyOf(buf, pos));
    }

    final void resetOutput() {
        pos = 0;
        prefixLen = 0;
        prefixDepth = 0;
    }

    /** Writes the {@code Action=...&Version=...} preamble that every Query request opens with. */
    @SuppressWarnings("deprecation")
    final void appendHeader(String action, String version) {
        ensureCapacity(ACTION_PREFIX.length + action.length() + VERSION_PREFIX.length + version.length());
        System.arraycopy(ACTION_PREFIX, 0, buf, pos, ACTION_PREFIX.length);
        pos += ACTION_PREFIX.length;
        action.getBytes(0, action.length(), buf, pos);
        pos += action.length();
        System.arraycopy(VERSION_PREFIX, 0, buf, pos, VERSION_PREFIX.length);
        pos += VERSION_PREFIX.length;
        version.getBytes(0, version.length(), buf, pos);
        pos += version.length();
    }

    final void pushPrefix(byte[] name) {
        pushDepth();
        reservePrefix(name.length + (prefixLen > 0 ? 1 : 0));
        if (prefixLen > 0) {
            prefixBuf[prefixLen++] = '.';
        }
        System.arraycopy(name, 0, prefixBuf, prefixLen, name.length);
        prefixLen += name.length;
    }

    final void pushPrefixWithIndex(byte[] name, int index) {
        pushDepth();
        reservePrefix((prefixLen > 0 ? 1 : 0) + name.length + 1 + NumberCodec.digitCount(index));
        if (prefixLen > 0) {
            prefixBuf[prefixLen++] = '.';
        }
        System.arraycopy(name, 0, prefixBuf, prefixLen, name.length);
        prefixLen += name.length;
        prefixBuf[prefixLen++] = '.';
        prefixLen = NumberCodec.writeInt(prefixBuf, prefixLen, index);
    }

    /**
     * Appends {@code head}, which carries its own trailing separator, followed by {@code index}.
     *
     * <p>The folded form of {@link #pushPrefixWithIndex}: a generated codec knows every static
     * segment ahead of the index, so it supplies them as one constant instead of one push each.
     */
    final void pushPrefixIndexed(byte[] head, int index) {
        pushDepth();
        reservePrefix((prefixLen > 0 ? 1 : 0) + head.length + NumberCodec.digitCount(index));
        if (prefixLen > 0) {
            prefixBuf[prefixLen++] = '.';
        }
        System.arraycopy(head, 0, prefixBuf, prefixLen, head.length);
        prefixLen += head.length;
        prefixLen = NumberCodec.writeInt(prefixBuf, prefixLen, index);
    }

    final void pushIndexPrefix(int index) {
        pushDepth();
        reservePrefix((prefixLen > 0 ? 1 : 0) + NumberCodec.digitCount(index));
        if (prefixLen > 0) {
            prefixBuf[prefixLen++] = '.';
        }
        prefixLen = NumberCodec.writeInt(prefixBuf, prefixLen, index);
    }

    final void popPrefix() {
        prefixLen = prefixStack[--prefixDepth];
    }

    /**
     * Appends a URL-encoded string value.
     *
     * <p>The caller must have reserved {@code value.length() * 3} bytes, which is exact for ASCII.
     * A non-ASCII character needs up to nine, so the widened reservation is taken here rather than
     * being pushed onto every call site: missing it is how a multi-byte value overruns the buffer.
     */
    final void appendUrlEncoded(String value) {
        byte[] latin1 = CompactStringAccess.latin1Bytes(value);
        int next;
        if (latin1 != null) {
            next = QueryUrlEncoding.writeAsciiUrlEncoded(buf, pos, latin1);
            if (next < 0) {
                ensureCapacity(latin1.length * QueryUrlEncoding.MAX_BYTES_PER_LATIN1_BYTE);
                next = QueryUrlEncoding.writeLatin1UrlEncoded(buf, pos, latin1);
            }
        } else {
            next = QueryUrlEncoding.writeAsciiUrlEncoded(buf, pos, value);
            if (next < 0) {
                ensureCapacity(value.length() * QueryUrlEncoding.MAX_BYTES_PER_CHAR);
                next = QueryUrlEncoding.writeUrlEncoded(buf, pos, value);
            }
        }
        pos = next;
    }

    /** Appends {@code len} URL-encoded ASCII bytes. The caller must have reserved {@code len * 3}. */
    final void appendUrlEncodedBytes(byte[] data, int len) {
        pos = QueryUrlEncoding.writeUrlEncodedBytes(buf, pos, data, len);
    }

    /** Appends a URL-encoded HTTP date. The caller must have reserved {@link #MAX_HTTP_DATE_BYTES}. */
    final void appendHttpDate(Instant value) {
        int len = TimestampCodec.writeHttpDate(httpDateTmp, 0, value);
        pos = QueryUrlEncoding.writeUrlEncodedBytes(buf, pos, httpDateTmp, len);
    }

    private void pushDepth() {
        if (prefixDepth >= prefixStack.length) {
            prefixStack = Arrays.copyOf(prefixStack, prefixStack.length * 2);
        }
        prefixStack[prefixDepth++] = prefixLen;
    }

    private void reservePrefix(int needed) {
        if (prefixLen + needed > prefixBuf.length) {
            prefixBuf = Arrays.copyOf(prefixBuf, Math.max(prefixLen + needed, prefixBuf.length * 2));
        }
    }
}
