[versions]
junit5 = "6.0.0"
hamcrest = "3.0"
smithy = "1.63.0"
jmh = "0.7.3"
test-logger-plugin = "4.0.0"
spotbugs = "6.0.22"
spotless = "8.0.0"
smithy-gradle-plugins = "1.3.0"
assertj = "3.27.6"
jackson = "2.20.0"
netty = "4.2.7.Final"
dep-analysis = "3.4.0"
aws-sdk = "2.36.3"
osdetector = "1.7.3"
accp = "2.4.1" # Amazon Corretto Crypto Provider
jreleaser = "1.20.0"
picocli = "4.7.7"
jline = "3.30.6"
graalvm-native = "0.11.2"
shadow = "8.3.9"

[libraries]
smithy-model = { module = "software.amazon.smithy:smithy-model", version.ref = "smithy" }
smithy-codegen = { module = "software.amazon.smithy:smithy-codegen-core", version.ref = "smithy" }
smithy-aws-traits = { module = "software.amazon.smithy:smithy-aws-traits", version.ref = "smithy" }
smithy-protocol-traits = { module = "software.amazon.smithy:smithy-protocol-traits", version.ref = "smithy" }
smithy-protocol-test-traits = { module = "software.amazon.smithy:smithy-protocol-test-traits", version.ref = "smithy"}
smithy-aws-protocol-tests = { module = "software.amazon.smithy:smithy-aws-protocol-tests", version.ref = "smithy" }
smithy-protocol-tests = { module = "software.amazon.smithy:smithy-protocol-tests", version.ref = "smithy" }
smithy-validation-model = { module = "software.amazon.smithy:smithy-validation-model", version.ref = "smithy" }
smithy-jmespath = { module = "software.amazon.smithy:smithy-jmespath", version.ref = "smithy" }
smithy-waiters = { module = "software.amazon.smithy:smithy-waiters", version.ref = "smithy" }
smithy-utils = { module = "software.amazon.smithy:smithy-utils", version.ref = "smithy" }
smithy-traitcodegen = { module = "software.amazon.smithy:smithy-trait-codegen", version.ref = "smithy" }
smithy-rules = { module = "software.amazon.smithy:smithy-rules-engine", version.ref = "smithy" }
smithy-aws-endpoints = { module = "software.amazon.smithy:smithy-aws-endpoints", version.ref = "smithy" }

# AWS SDK for Java V2 adapters.
aws-sdk-retries-spi = {module = "software.amazon.awssdk:retries-spi", version.ref = "aws-sdk"}
aws-sdk-retries = {module = "software.amazon.awssdk:retries", version.ref = "aws-sdk"}
aws-sdk-core = {module = "software.amazon.awssdk:sdk-core", version.ref = "aws-sdk"}
aws-sdk-auth = {module = "software.amazon.awssdk:auth", version.ref = "aws-sdk"}

jackson-core = {module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson"}

netty-all = {module = "io.netty:netty-all", version.ref = "netty"}

# CLI related dependencies
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
jline-terminal = { module = "org.jline:jline-terminal", version.ref = "jline" }
jline-reader = { module = "org.jline:jline-reader", version.ref = "jline" }

# Test dependencies
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj"}

# plugin artifacts for buildsrc plugins
test-logger-plugin = { module = "com.adarshr:gradle-test-logger-plugin", version.ref = "test-logger-plugin" }
spotbugs = { module = "com.github.spotbugs.snom:spotbugs-gradle-plugin", version.ref = "spotbugs" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
smithy-gradle-base = { module = "software.amazon.smithy.gradle:smithy-base", version.ref = "smithy-gradle-plugins" }
dependency-analysis = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dep-analysis" }

[plugins]
jmh = { id = "me.champeau.jmh", version.ref = "jmh" }
osdetector = { id = "com.google.osdetector", version.ref = "osdetector" }
smithy-gradle-jar = { id = "software.amazon.smithy.gradle.smithy-jar", version.ref = "smithy-gradle-plugins" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-native" }
shadow = { id = "com.gradleup.shadow", version.ref =  "shadow"}
