#!/bin/bash

# Name of your JAR file
JAR_NAME="dynamic-client-cli-0.0.1.jar"

# Path to your JAR file
# Adjust this path as needed
JAR_PATH="./build/libs/$JAR_NAME"

# Check if the JAR file exists
if [ ! -f "$JAR_PATH" ]; then
    echo "Error: $JAR_PATH not found!"
    exit 1
fi

# Run the Java application with all passed arguments
java -cp "$JAR_PATH" software.amazon.smithy.java.cli.CoralXRunner "$@"