/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

package software.amazon.smithy.java.xml;

import static org.assertj.core.api.Assertions.assertThat;

import java.nio.ByteBuffer;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.IdentityHashMap;
import java.util.List;
import java.util.Random;
import java.util.Set;
import java.util.stream.IntStream;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import software.amazon.smithy.java.core.schema.Schema;
import software.amazon.smithy.java.core.schema.SerializableShape;
import software.amazon.smithy.java.core.schema.SerializableStruct;
import software.amazon.smithy.java.core.schema.ShapeBuilder;
import software.amazon.smithy.java.core.schema.TraitKey;
import software.amazon.smithy.java.core.serde.SerializationException;

/**
 * Feeds the generated reader damaged documents and holds it to the dispatch reader's behaviour.
 *
 * <p>{@code RuntimeXmlCodegenTest} covers documents chosen by hand, which means it covers the mistakes
 * that were thought of. This covers the ones that were not: it takes a well-formed document for each
 * shape in the test model and corrupts it at the byte level, which reaches states no schema-driven writer
 * and no hand-written case would reach — a tag name cut in half, a quote deleted so an attribute swallows
 * the rest of the element, a duplicated span that closes an element twice.
 *
 * <p>Three things are required of every document. Neither reader may lose control of where it is in the
 * buffer, whatever the other one does. When both read the document, they must read it as the same value.
 * When one reads it and the other does not, that is a bug in one of them, except across the structural
 * split {@link #mustAgree} documents. Which of several defects a reader names first is not required to
 * match, because that follows from member order rather than from either reader being right.
 *
 * <p>Every seed is fixed, so this is a fuzzer's coverage with a unit test's reproducibility: a failure
 * names the seed and iteration and prints the exact bytes that caused it. It is not a substitute for
 * {@code :codecs:xml-codec:fuzz}, which explores far more inputs, but that task cannot currently start:
 * its seed corpus is generated by {@code ShapeUtils.RandomShapeGenerator}, whose {@code isNull} returns a
 * coin flip without consulting {@code @sparse}, so serializing the seeds throws before any fuzzing
 * happens. That is a pre-existing failure shared by the JSON and CBOR fuzz tasks.
 */
final class RuntimeXmlCodegenMutationTest {

    /**
     * 80,000 documents across the forty seeds, of which about 3,600 still parse. High enough that the
     * value comparison happens thousands of times, low enough that the whole class runs in a second.
     */
    private static final int MUTATIONS_PER_SEED = 2000;

    /** Bytes worth inserting, because corrupting XML structure finds more than corrupting text does. */
    private static final byte[] INTERESTING = "<>/\"'&= \t\n:?!-".getBytes(StandardCharsets.UTF_8);

    /** What a clean rejection collapses to, so two readers can disagree about the wording. */
    private static final String REJECTED = "rejected";

    /** Prefix for the outcomes no reader may produce, whatever the other one does. */
    private static final String LOST_CONTROL = "lost control: ";

    private static XmlCodec generated() {
        return XmlCodec.builder().useNative(true).runtimeCodegen(true).build();
    }

    private static XmlCodec interpreted() {
        return XmlCodec.builder().useNative(true).runtimeCodegen(false).build();
    }

    static IntStream seeds() {
        return IntStream.rangeClosed(1, 40);
    }

    @ParameterizedTest(name = "seed {0}")
    @MethodSource("seeds")
    void mutatedDocumentsReadLikeTheInterpretedPath(int seed) {
        List<SerializableStruct> shapes = new ArrayList<>();
        for (var argument : RuntimeXmlCodegenTest.shapes()) {
            shapes.add((SerializableStruct) argument.get()[1]);
        }

        List<byte[]> documents = new ArrayList<>(shapes.size());
        try (var interpreted = interpreted()) {
            for (SerializableStruct shape : shapes) {
                documents.add(bytes(interpreted.serialize(shape)));
            }
        }

        int stillReadable = 0;
        Random random = new Random(seed);
        try (var generated = generated(); var interpreted = interpreted()) {
            for (int iteration = 0; iteration < MUTATIONS_PER_SEED; iteration++) {
                int index = random.nextInt(shapes.size());
                SerializableStruct shape = shapes.get(index);
                byte[] mutated = mutate(random, documents.get(index));
                Object generatedOutcome = readOutcome(generated, shape, mutated);
                Object interpretedOutcome = readOutcome(interpreted, shape, mutated);
                String where = String.format("seed %d iteration %d: %s", seed, iteration, describe(mutated));

                assertThat(List.of(generatedOutcome, interpretedOutcome))
                        .as(where)
                        .noneMatch(RuntimeXmlCodegenMutationTest::lostControl);

                if (mustAgree(generatedOutcome, interpretedOutcome, shape)) {
                    assertThat(generatedOutcome).as(where).isEqualTo(interpretedOutcome);
                }
                if (interpretedOutcome instanceof SerializableShape) {
                    stillReadable++;
                }
            }
        }

        // Most mutations destroy the document, which is the point, but a mutator that destroyed all of them
        // would satisfy every assertion above without ever comparing a value. So the interesting case is
        // shown to happen rather than assumed. The seeds are fixed, so this is a fact about the corpus and
        // not a flaky threshold: the lowest of the forty leaves 69 documents readable and the highest 117.
        assertThat(stillReadable).as("seed %d left almost no document readable", seed).isGreaterThan(50);
    }

    /**
     * Whether these two outcomes have to be the same outcome.
     *
     * <p>A mutated document usually has several independent defects, and the two readers do not visit a
     * structure's members in the same order, so they do not necessarily reach the same defect first. The
     * dispatch reader walks {@code schema.members()}, which {@code SchemaBuilder.sortMembers} has reordered
     * to put required members without a default first; the generated reader walks attributes before
     * elements, in the order its plan lists them. Handed a start tag with both an unparseable number and a
     * truncated entity reference, one names the number and the other names the entity. Neither is wrong
     * about the document, and pinning the answer would pin the member order rather than the reader, so two
     * failures are not compared. Both readers still have to fail.
     *
     * <p>The one case where a disagreement about failing at all is allowed is a structure with a flattened
     * member. The dispatch reader reads those in two passes, because a flattened member's elements are
     * interleaved with its siblings and it cannot know a run has ended until it sees something else: pass
     * one buffers each span with {@code skipElement}, pass two replays it. The generated reader knows from
     * the schema which element names belong to which member, so it reads in one document-order pass. On a
     * well-formed document that is invisible; on a damaged one it moves the line in both directions.
     *
     * <ul>
     *     <li>The dispatch reader rejects more. {@code skipElement} validates every end tag name in the
     *     span it buffers, so it rejects {@code <items>x</itemsX>} inside a flattened list. Its own
     *     single-pass code does not: handed that corruption in a wrapped list it accepts it, and
     *     {@code readMapContent} consumes a map key's end tag without checking its name, exactly as the
     *     generated reader does. This is a rule it enforces in one place and not the others, not a rule the
     *     generated reader is failing to enforce.
     *     <li>The dispatch reader also accepts more. Buffering a span only needs the tags in it to balance,
     *     so damage that keeps them balanced survives pass one and can be dropped in pass two:
     *     {@code <entries>><key>k</key><value>v</value><>v</value></entries>} reads as a one-entry map,
     *     while the generated reader reaches the stray {@code </value>} in document order and rejects.
     * </ul>
     *
     * <p>What holds with no exception is that the readers never read one document as two different values.
     * Disagreeing about whether a corrupt document is XML at all is tolerable; disagreeing about what it
     * means is not. Well-formed documents are held to byte and value identity in
     * {@code RuntimeXmlCodegenTest}, and neither reader may lose control on any input at all.
     */
    private static boolean mustAgree(
            Object generatedOutcome,
            Object interpretedOutcome,
            SerializableStruct shape
    ) {
        boolean generatedRead = generatedOutcome instanceof SerializableShape;
        boolean interpretedRead = interpretedOutcome instanceof SerializableShape;
        if (generatedRead && interpretedRead) {
            return true;
        }
        if (!generatedRead && !interpretedRead) {
            return false;
        }
        return !hasFlattenedMember(shape.schema());
    }

    /** Whether {@code schema} reaches a flattened member, and so a two-pass read. */
    private static boolean hasFlattenedMember(Schema schema) {
        return hasFlattenedMember(schema.isMember() ? schema.memberTarget() : schema,
                Collections.newSetFromMap(new IdentityHashMap<>()));
    }

    private static boolean hasFlattenedMember(Schema schema, Set<Schema> seen) {
        if (!seen.add(schema)) {
            return false;
        }
        for (Schema member : schema.members()) {
            if (member.hasTrait(TraitKey.XML_FLATTENED_TRAIT)
                    || hasFlattenedMember(member.memberTarget(), seen)) {
                return true;
            }
        }
        return false;
    }

    /** Applies one to three corruptions, so a mutation can land inside what an earlier one produced. */
    private static byte[] mutate(Random random, byte[] document) {
        byte[] result = document.clone();
        int rounds = 1 + random.nextInt(3);
        for (int i = 0; i < rounds && result.length > 0; i++) {
            result = switch (random.nextInt(5)) {
                case 0 -> replaceByte(random, result);
                case 1 -> deleteRange(random, result);
                case 2 -> insertByte(random, result);
                case 3 -> duplicateRange(random, result);
                default -> truncate(random, result);
            };
        }
        return result;
    }

    private static byte[] replaceByte(Random random, byte[] document) {
        document[random.nextInt(document.length)] = interestingByte(random);
        return document;
    }

    private static byte[] insertByte(Random random, byte[] document) {
        int at = random.nextInt(document.length + 1);
        byte[] result = new byte[document.length + 1];
        System.arraycopy(document, 0, result, 0, at);
        result[at] = interestingByte(random);
        System.arraycopy(document, at, result, at + 1, document.length - at);
        return result;
    }

    private static byte[] deleteRange(Random random, byte[] document) {
        int from = random.nextInt(document.length);
        int length = 1 + random.nextInt(Math.min(16, document.length - from));
        byte[] result = new byte[document.length - length];
        System.arraycopy(document, 0, result, 0, from);
        System.arraycopy(document, from + length, result, from, document.length - from - length);
        return result;
    }

    private static byte[] duplicateRange(Random random, byte[] document) {
        int from = random.nextInt(document.length);
        int length = 1 + random.nextInt(Math.min(32, document.length - from));
        byte[] result = new byte[document.length + length];
        System.arraycopy(document, 0, result, 0, from + length);
        System.arraycopy(document, from, result, from + length, length);
        System.arraycopy(document, from + length, result, from + 2 * length, document.length - from - length);
        return result;
    }

    private static byte[] truncate(Random random, byte[] document) {
        byte[] result = new byte[random.nextInt(document.length)];
        System.arraycopy(document, 0, result, 0, result.length);
        return result;
    }

    /**
     * Weighted towards bytes that mean something to a parser; a uniformly random byte almost always lands
     * in text, where nothing interesting happens.
     */
    private static byte interestingByte(Random random) {
        return random.nextInt(4) == 0
                ? (byte) random.nextInt(256)
                : INTERESTING[random.nextInt(INTERESTING.length)];
    }

    /**
     * The shape read, or a description of the failure, so a rejection can be compared like a value.
     *
     * <p>Every rejection reported through {@link SerializationException} collapses to {@link #REJECTED}.
     * Two independently written parsers will always word a complaint differently, and requiring them to
     * agree on the wording would be a test of the wording.
     *
     * <p>Any other exception keeps its class and message, because that is not a rejection: it is the reader
     * failing in a way a caller catching the codec's own exception type will not catch. Both readers do it
     * for a malformed number, identically, so keeping the detail costs nothing and would show one of them
     * starting to do it somewhere the other does not.
     *
     * <p>Running off the end of the buffer or off the end of the stack is different again: it is not an
     * answer about the document, it is the reader losing track of where it is. Neither reader may do it even
     * if the other one does, so those get their own prefix and {@link #lostControl(Object)} fails the test
     * on them outright instead of comparing them.
     */
    private static Object readOutcome(XmlCodec codec, SerializableStruct shape, byte[] document) {
        ShapeBuilder<? extends SerializableShape> builder = shape.schema().shapeBuilder();
        try {
            return codec.deserializeShape(ByteBuffer.wrap(document), builder);
        } catch (SerializationException e) {
            return lostControl(e) ? LOST_CONTROL + describe(e) : REJECTED;
        } catch (IndexOutOfBoundsException | NegativeArraySizeException e) {
            return LOST_CONTROL + describe(e);
        } catch (RuntimeException e) {
            return describe(e);
        } catch (StackOverflowError e) {
            return LOST_CONTROL + "java.lang.StackOverflowError";
        }
    }

    /** True for an outcome no reader may produce; see {@link #readOutcome}. */
    private static boolean lostControl(Object outcome) {
        return outcome instanceof String s && s.startsWith(LOST_CONTROL);
    }

    /**
     * Whether a rejection was really a bounds failure the codec wrapped on its way out.
     *
     * <p>Only asked of {@link SerializationException}: a bounds exception is a legitimate internal signal
     * elsewhere, and {@code new BigDecimal("")} in particular reports an empty string by catching one and
     * rethrowing it as a {@code NumberFormatException} with the bounds failure as its cause.
     */
    private static boolean lostControl(SerializationException thrown) {
        for (Throwable cause = thrown.getCause(); cause != null; cause = cause.getCause()) {
            if (cause instanceof IndexOutOfBoundsException || cause instanceof NegativeArraySizeException) {
                return true;
            }
        }
        return false;
    }

    private static String describe(Throwable thrown) {
        return thrown.getClass().getName() + ": " + thrown.getMessage();
    }

    /**
     * Renders a mutated document so it can be pasted back into a test.
     *
     * <p>Not {@code new String(bytes, UTF_8)}: a mutation inserts arbitrary bytes, and decoding those turns
     * each one into a replacement character, so the document in the failure message is not the document
     * that failed.
     */
    private static String describe(byte[] document) {
        StringBuilder result = new StringBuilder(document.length);
        for (byte b : document) {
            int value = b & 0xFF;
            if (value >= 0x20 && value < 0x7F && value != '\\') {
                result.append((char) value);
            } else {
                result.append(String.format("\\x%02X", value));
            }
        }
        return result.toString();
    }

    private static byte[] bytes(ByteBuffer buffer) {
        byte[] copy = new byte[buffer.remaining()];
        buffer.duplicate().get(copy);
        return copy;
    }
}
