name: Updates the main-codegen branch if any codegen updates are merged.
on:
  workflow_dispatch: # on button click
  pull_request:
    branches: ["main"]
    types: [closed]
    paths: ["codegen/**"]

jobs:
  update-on-merge:
    if: ${{ github.event.pull_request.merged }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: 'main'
          token: "${{ secrets.PR_TOKEN }}"

      - uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Rebuild project
        run: ./gradlew clean build --stacktrace

      - name: Set up git configuration
        run: |
          git config --global user.email "github-smithy-automation@amazon.com"
          git config --global user.name "smithy-automation"

      - name: Add generated files
        run: |
          git checkout -b main-codegen
          git add -f codegen/core/build/generated-src/
          git add -f codegen/client/build/generated-src/
          git add -f codegen/server/build/generated-src/

      - name: Create and push update
        run: |
          git commit -m "Update generated code for PR: ${{ github.event.pull_request.number }}"
          git push -f -u origin main-codegen
